version: '3.5'

services:

   d0000-prd-exemplo-api:
    image: harbor.sgi.ms.gov.br/Time/d0000.prd.exemplo-api.v1:__tagDeploy__
        
    networks:
      - proxy_net
    
    environment:
      sid: D0000
      app_name: exemplo-api
      app_version: __tagDeploy__
      team: time

    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 700M
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      placement:
        constraints: 
          - node.labels.region == prd
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy_net"
        - "traefik.http.routers.d0000-prd-exemplo-api.rule=Host(`gw.sgi.ms.gov.br`) && PathPrefix(`/d0000`)"
        - "traefik.http.routers.d0000-prd-exemplo-api.service=d0000-prd-exemplo-api"
        - "traefik.http.routers.d0000-prd-exemplo-api.entrypoints=http"
        - "traefik.http.services.d0000-prd-exemplo-api.loadbalancer.server.port=80"
networks:
  proxy_net:
    external: true